theme: null
# # Optional
# andersdjohnson:
#   # Use Google Analytics ID
#   google_analytics: "G-123456789"
#   # Show badges for npm
#   npm_name: fetch-paginate
#   # Show a badge for Travis CI
#   travis: true
