title: AndersDJohnson Jekyll Theme
description: AndersDJohnson Jekyll Theme

lang: en-US
branch: master

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

# plugins:
#   - jekyll-github-metadata

exclude:
  - vendor/bundle
  - node_modules
  - js
  - sass

theme: null
